ExportDataTableToExcelMVC4/Controllers/ImportDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using ExportDataTableToExcelInMVC4.Models;
using System.Configuration;
using System.IO;
using System.Data;
using System.Data.Entity;
using System.Data.Common;
using System.Data.OleDb;
using System.Data.SqlClient;

using System.Web.Mvc.Html;
using System.Text.RegularExpressions;

namespace ExportDataTableToExcelMVC4.Controllers
{
    public class Factura
    {
        public double CodigoCliente { get; set; }
        public double Importe { get; set; }
        public string Concepto { get; set; }
        public string TipoIva { get; set; }
        public double CodigoMarca { get; set; }
    }

    public class ImportDataController : Controller
    {
        public ActionResult Import()
        { return View(); }

        public ActionResult Importexcel()
        {
            //DEFINICIONES
            ImportarModel ImportarModelObj = new ImportarModel();//Se instancia la variable del model para utilizar sus valores estaticos
            //Listas de errores
            List<int> errorCodigoClienteList = new List<int>();//Se instancian las listas de errores 
            List<int> errorImporteList = new List<int>();      //para guardar los indices de celdas null
            List<int> errorConceptoList = new List<int>();
            List<int> errorTipoIvaList = new List<int>();
            List<int> errorCodigoMarcaList = new List<int>();
            List<int> errorCodigoClienteCheckListIndex = new List<int>();//Lista con indices de CodigoCliente no presentes en DB 
            List<object> errorCodigoClienteCheckList = new List<object>();//Lista con valores de CodigoCliente no presentes en DB
            //Listas de invalidChar
            List<int> invalidCharCodigoClienteList = new List<int>();//Se instancian las listas de invalidChar 
            List<int> invalidCharImporteList = new List<int>();      //para guardar los indices de celdas con invalidChar
            List<int> invalidCharConceptoList = new List<int>();
            List<int> invalidCharTipoIvaList = new List<int>();
            List<int> invalidCharCodigoMarcaList = new List<int>();
            //Lista con valores de CodigoCliente presentes en la DB
            List<object> codigoClienteDBList = new List<object>();

            //Loader de excel            
            string path1 = string.Format("{0}/{1}", Server.MapPath("~/Content/UploadedFolder"), Request.Files["FileUpload1"].FileName);
            if (System.IO.File.Exists(path1)) System.IO.File.Delete(path1);

            //CONNECTION STRINGS
            //Base de datos
            Request.Files["FileUpload1"].SaveAs(path1);
            string sqlConnectionString = @"Data Source=.\SQLEXPRESS;Initial Catalog=excelMvcDB;Integrated Security=True";
            //Excel
            string excelConnectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + path1 +
                ";Extended Properties=Excel 12.0;Persist Security Info=False";
            OleDbConnection excelConnection = new OleDbConnection(excelConnectionString);
            //Comando SQL
            OleDbCommand cmd = new OleDbCommand("Select [CodigoCliente],[Importe],[Concepto],[TipoIva],[CodigoMarca]" +
                " from [Facturas$]", excelConnection);
                        
            //CHECKER CODIGOCLIENTE DB-EXCEL: Se crea una lista con los "codigoCliente" disponibles en la DB
            using (SqlConnection conexionDB = new SqlConnection(sqlConnectionString))
            {
                SqlCommand getCodigoClienteDB = new SqlCommand("Select * from FacturasRecord", conexionDB);
                conexionDB.Open();
                using (IDataReader dataReader = getCodigoClienteDB.ExecuteReader())
                {
                    while (dataReader.Read())
                    {
                        ListItem CodigoClienteDB = new ListItem(Convert.ToString(dataReader["CodigoCliente"]));
                        codigoClienteDBList.Add(CodigoClienteDB);//Se añaden los "codigoCliente" de la DB a la lista
                        ViewBag.codigoClienteDBList = codigoClienteDBList;//Se alamacena la lista en viewBag xra su uso
                    }
                }
            }
            //Seleccion y Carga del archivo
            if (Request.Files["FileUpload1"].ContentLength > 0)
            {
                try
                {   //CHECKER FORMATO EXCEL  
                    string extension = System.IO.Path.GetExtension(Request.Files["FileUpload1"].FileName);
                    if (extension != ".xlsx" && extension != ".xls")//Si no es excel: ExcelExtension=false y PopUpExcelExtensionError
                    {
                        ImportarModelObj.ExcelExtension = false;
                        ImportarModelObj.SuccessGlobal = false;
                        ImportarModelObj.Validated = false;
                        return View("ImportPopUps", ImportarModelObj);
                    }
                    else { ImportarModelObj.ExcelExtension = true; }
                    //CHECKER CONEXION EXCEL
                    try
                    {//(La conexion depende del Comando SQL "cmd":Columnas, nombre de la hoja y "excelConnection" ) 
                        excelConnection.Open();
                        int a = cmd.ExecuteNonQuery();
                        excelConnection.Close();
                        ImportarModelObj.ExcelConnection = true;
                    }
                    catch
                    {//Si falla la conexion ExcelConnection=false y PopUpExcelConnectionError
                        excelConnection.Close();
                        ImportarModelObj.ExcelConnection = false;
                        ImportarModelObj.SuccessGlobal = false;
                        ImportarModelObj.Validated = false;
                        return View("ImportPopUps", ImportarModelObj);
                    }
                    //INICIO CHECKERS CELDAS
                    OleDbDataAdapter da = new OleDbDataAdapter(cmd);//no se abre conexion xq el datAdapter incluye el "cmd" 
                    DataSet ds = new DataSet(); //Se crea dataset              
                    ds.Tables.Add("xlsImport");//Se añaden tablas a ds
                    da.Fill(ds, "xlsImport");//Se añaden datos a ds con comando cmd del dataAdapter                  
                    //Se crean columnas en la tabla xlsImport
                    ds.Tables["xlsImport"].Columns[0].ColumnName = "CodigoCliente";
                    ds.Tables["xlsImport"].Columns[1].ColumnName = "Importe";
                    ds.Tables["xlsImport"].Columns[2].ColumnName = "Concepto";
                    ds.Tables["xlsImport"].Columns[3].ColumnName = "TipoIva";
                    ds.Tables["xlsImport"].Columns[4].ColumnName = "CodigoMarca";
                    excelConnection.Close();//Se cierra conexion con excel

                    //Una vez creada la tabla xlsImport se asignan los formatos de cada columna
                    var datos = ds.Tables["xlsImport"].AsEnumerable();
                    var query = datos.Where(x => x.Field<string>("Concepto") != null).Select(x =>
                                new Factura
                                {
                                    CodigoCliente = x.Field<double>("CodigoCliente"),
                                    Importe = x.Field<double>("Importe"),
                                    Concepto = x.Field<string>("Concepto"),
                                    TipoIva = x.Field<string>("TipoIva"),
                                    CodigoMarca = x.Field<double>("CodigoMarca")
                                });

                    foreach (DataRow row in ds.Tables["xlsImport"].Rows)
                    {   
                        //CHEKER CARACTERES INVALIDOS
                        int index = ds.Tables["xlsImport"].Rows.IndexOf(row) + 2;//Se instancia el indice
                        object valueCodigoCliente = row["CodigoCliente"]; //Se instancian las celdas de las columnas seleccionadas
                        object valueImporte = row["Importe"];
                        object valueConcepto = row["Concepto"];
                        object valueTipoIva = row["TipoIva"];
                        object valueCodigoMarca = row["CodigoMarca"];
                        //Se convierte el valor de la celda en string 
                        string valueCodigoClienteString = Convert.ToString(valueCodigoCliente);
                        string valueImporteString = Convert.ToString(valueImporte);
                        string valueConceptoString = Convert.ToString(valueConcepto);
                        string valueTipoIvaString = Convert.ToString(valueTipoIva);
                        string valueCodigoMarcaString = Convert.ToString(valueCodigoMarca);
                        //Se crean strings vacias para rellenarlas con la string sin invalidChars,y así compararlas con las string de origen
                        string valueCodigoClienteStringClean = "";
                        string valueImporteStringClean = "";
                        string valueConceptoStringClean = "";
                        string valueTipoIvaStringClean = "";
                        string valueCodigoMarcaStringClean = "";
                        //Se replazan los caracteres invalidos 
                        valueCodigoClienteStringClean = Regex.Replace(valueCodigoClienteString, "([^0-9a-nA-No-zO-ZçÇñÑáéíóúäëïöü_ ])", "").Trim();
                        valueImporteStringClean = Regex.Replace(valueImporteString, "([^0-9a-nA-No-zO-ZçÇñÑáéíóúäëïöü_ ])", "").Trim();
                        valueConceptoStringClean = Regex.Replace(valueConceptoString, "([^0-9a-nA-No-zO-ZçÇñÑáéíóúäëïöü_ ])", "").Trim();
                        valueTipoIvaStringClean = Regex.Replace(valueTipoIvaString, "([^0-9a-nA-No-zO-ZçÇñÑáéíóúäëïöü_ ])", "").Trim();

ExportDataTableToExcelMVC4/Views/ImportData/Import.cshtml
@{
    ViewBag.Title = "Importar";
}
<script>
        $(document).ready(function () {
            // show when page load
            toastr.info('Selecciona un excel para añadirlo a la base de Datos');
        });
</script>
<p style="background-color: grey; color: white; font-size: 20pt; font-weight: bold; padding: 10px; text-align: center;">
    Importar Excel a la Base de Datos
</p>

@using (Html.BeginForm("Importexcel", "ImportData", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr><td></td><td><input type="file" id="FileUpload1" name="FileUpload1" /></td></tr>
        <tr><td></td><td><input type="submit" id="Submit" name="Importar" value="Submit" /></td></tr>
    </table>
}

<div class="popUpMessages">

    <!--partialContents. We use this in jQuery to locate them-->
    <!--data-url for the location of the partialview controller action-->
    <div class="partialContents" data-url="/Controllers/ImportDataController/Importexcel">
       <p>Seleccione un archivo excel y pulse Importar.</p>
    </div>   
</div>

ExportDataTableToExcelMVC4/Views/ImportData/ImportPopUp.cshtml
@{
    ViewBag.Title = "ImportPopUps";
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/toastr.min.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    @Scripts.Render("~/bundles/modernizr")

    <!--script AsyncPartials-->
    <!--scripts de PopUps-->
    <script>
        $(document).ready(function () {
            // show when page load
            toastr.error('Error: un valor de la columna CodigoCliente no esta en formato correcto');
        });
    </script>
    <!--END scripts de los PopUps-->
</head>
<body>
    <p style="background-color: grey; color: white; font-size: 20pt; font-weight: bold; padding: 10px; text-align: center;">
        Importar Excel a la Base de Datos
    </p>

    @using (Html.BeginForm("Importexcel", "ImportData", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <table>
            <tr><td></td><td><input type="file" id="FileUpload1" name="FileUpload1" /></td></tr>
            <tr><td></td><td><input type="submit" id="Submit" name="Submit" value="Submit" /></td></tr>
        </table>
    }

    <div class="popUpMessages">
        <!--partialContents. We use this in jQuery to locate them-->
        <!--data-url for the location of the partialview controller action-->
        <div class="partialContents" data-url="~/Views/ImportData/ImportPopUps.cshtml">
               @if (Model.Success)
               {
                @:toastr.success("@Model.Message");
            }
               else if (!Model.Success && !String.IsNullOrWhiteSpace(Model.Message))
               {
                @:toastr.error("@Model.Message");
            }
            </div>
       <div class="popUps" data-url="/Controllers/ImportDataController/ImportPopUps">
        <img src="~/assets/img/ajax-loader.gif" />loading.... <!--message and image to show an AJAX indicator that we are working on that area.-->
        </div>
    </div>
</body>
</html>

ExportDataTableToExcelMVC4/Views/ImportData/ImportPopUps.cshtml
@{
    ViewBag.Title = "ImportPopUps";
}
<!--Titulo-->
<p style="background-color: grey; color: white; font-size: 20pt; font-weight: bold; padding: 10px; text-align: center;">
    Importar Excel a la Base de Datos
</p>
<!--Seleccion de excel-->
@using (Html.BeginForm("Importexcel", "ImportData", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr><td></td><td><input type="file" id="FileUpload1" name="FileUpload1" /></td></tr>
        <tr><td></td><td><input type="submit" id="Submit" name="Submit" value="Submit" /></td></tr>
    </table>
     <!--PopUp de SuccessGlobal=True-->
    if (Model.Importable)
    {
        @Html.Partial("~/Views/ImportData/PopUpsGlobal/PopUpImported.cshtml", (object)Model)return;
    }
}

<div class="col-md-12">
    <!--/ Seleccion de excel-->
    @if (!Model.Importable)
    {        <h4>ERRORES</h4>
        if (!Model.Validated)
        {
            if (!Model.ExcelExtension && !Model.ExcelConnection)
            {//Si es extension erronea tendrá tambien conexion erronea, por lo q no tiene sentido mostrar ambos errores.
                @Html.Partial("~/Views/ImportData/PopUpsValidation/PopUpExcelExtensionError.cshtml", (object)Model)
                @Html.Partial("~/Views/ImportData/PopUpsGlobal/PopUpGlobalError.cshtml", (object)Model)return;//Se corta el flujo ya que el resto de valores dará null
            }
            if (Model.ExcelExtension && !Model.ExcelConnection)
            {
                @Html.Partial("~/Views/ImportData/PopUpsValidation/PopUpExcelConnectionError.cshtml", (object)Model)
                @Html.Partial("~/Views/ImportData/PopUpsGlobal/PopUpGlobalError.cshtml", (object)Model)return;//Se corta el flujo ya que el resto de valores dará null
            }
    <!--PopUp de Checker CodigoClienteDB-EXCEL=False-->
            if (!Model.SuccesCodigoClienteCheck)//CodigoClienteCheck Valor
            {
                @Html.Partial("~/Views/ImportData/PopUpsValidation/PopUpCodigoClienteCheckError.cshtml", (object)Model)
                if (!Model.SuccesCodigoClienteCheck)//CodigoClienteCheck Indice
                {@Html.Partial("~/Views/ImportData/PopUpsValidation/PopUpCodigoClienteCheckIndexError.cshtml", (object)Model)}
            }
        }
        <!--PopUps de error de Success y muestra de detalles del error-->

    <!--PopUps de InvalidChar=True-->
        if (Model.InvalidCharGlobal)
        {
            @Html.Partial("~/Views/ImportData/PopUpsInvalidChar/InvalidCharSolution.cshtml", (object)Model)
            if (Model.CodigoClienteInvalidChar)//CodigoCliente
            {@Html.Partial("~/Views/ImportData/PopUpsInvalidChar/InvalidCharCodigoCliente.cshtml", (object)Model);
            }
            if (Model.ImporteInvalidChar)//Importe
            { @Html.Partial("~/Views/ImportData/PopUpsInvalidChar/InvalidCharImporte.cshtml", (object)Model);
            }
            if (Model.ConceptoInvalidChar)//Concepto
            { @Html.Partial("~/Views/ImportData/PopUpsInvalidChar/InvalidCharConcepto.cshtml", (object)Model);
            }
            if (Model.CodigoMarcaInvalidChar)//CodigoMarca
            { @Html.Partial("~/Views/ImportData/PopUpsInvalidChar/InvalidCharCodigoMarca.cshtml", (object)Model);
            }
            if (Model.TipoIvaInvalidChar)//TipoIva
            { @Html.Partial("~/Views/ImportData/PopUpsInvalidChar/InvalidCharTipoIva.cshtml", (object)Model);
            }
        }
    <!--PopUp de SuccessGlobal=False-->
        if (!Model.SuccessGlobal)
        {  <!--PopUps de Success=False-->
            @Html.Partial("~/Views/ImportData/PopUpsSuccess/PopUpSuccessErrorSolution.cshtml", (object)Model)
            if (!Model.SuccessCodigoCliente)//CodigoCliente
            {@Html.Partial("~/Views/ImportData/PopUpsSuccess/PopUpCodigoClienteError.cshtml", (object)Model)}
            if (!Model.SuccessImporte)//Importe
            {@Html.Partial("~/Views/ImportData/PopUpsSuccess/PopUpImporteError.cshtml", (object)Model)}
            if (!Model.SuccessCodigoMarca)//CodigoMarca
            {@Html.Partial("~/Views/ImportData/PopUpsSuccess/PopUpCodigoMarcaError.cshtml", (object)Model)}
            if (!Model.SuccessConcepto)//Concepto
            {@Html.Partial("~/Views/ImportData/PopUpsSuccess/PopUpConceptoError.cshtml", (object)Model)}
            if (!Model.SuccessTipoIva)//TipoIva
            {@Html.Partial("~/Views/ImportData/PopUpsSuccess/PopUpTipoIvaError.cshtml", (object)Model)}
        }
        @Html.Partial("~/Views/ImportData/PopUpsGlobal/PopUpGlobalError.cshtml", (object)Model)


    }
    <div class="clearfix"></div>
</div>

ExportDataTableToExcelMVC4/Views/ImportData/PopUpCodigoMarca.cshtml
@model ExportDataTableToExcelInMVC4.Models.ImportarModel

<!--scripts de PopUps-->
<script>
        $(document).ready(function () {
            // show when page load
            toastr.error('Error: un valor de la columna CodigoMarca no esta en formato correcto');
        });
</script>
<!--END scripts de los PopUps-->
<p>CodigoMarca:</p>
@foreach (var index in ViewBag.errorCodigoMarcaList)
{
    <ul>
        <li>@index</li>
    </ul>
}